<?php  
$dataappend = fopen('demo.txt', 'a');//opens file in append mode  
fwrite($dataappend, ' this is generated by Pratik Jha. ');  
fclose($dataappend);  
  
echo "File appended successfully";  
?>  